#!/bin/bash
ssh 192.168.133.210 "hammer -u admin -p redhat  host create --name $1  --compute-resource-id=1 --hostgroup-id=$3"
ssh 192.168.133.210 "hammer -u admin -p redhat  host start --name $1.testlab.local"
ssh 192.168.133.210 "/opt/scripts/appdeploy $1 $2 $3 $4"

